'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ScoutCheckboxCustomEvent, type ScoutInputCustomEvent } from "@scouterna/ui-webc";
import { ScoutBottomBarItem as ScoutBottomBarItemElement, defineCustomElement as defineScoutBottomBarItem } from "@scouterna/ui-webc/dist/components/scout-bottom-bar-item.js";
import { ScoutBottomBar as ScoutBottomBarElement, defineCustomElement as defineScoutBottomBar } from "@scouterna/ui-webc/dist/components/scout-bottom-bar.js";
import { ScoutButton as ScoutButtonElement, defineCustomElement as defineScoutButton } from "@scouterna/ui-webc/dist/components/scout-button.js";
import { ScoutCard as ScoutCardElement, defineCustomElement as defineScoutCard } from "@scouterna/ui-webc/dist/components/scout-card.js";
import { ScoutCheckbox as ScoutCheckboxElement, defineCustomElement as defineScoutCheckbox } from "@scouterna/ui-webc/dist/components/scout-checkbox.js";
import { ScoutField as ScoutFieldElement, defineCustomElement as defineScoutField } from "@scouterna/ui-webc/dist/components/scout-field.js";
import { ScoutInput as ScoutInputElement, defineCustomElement as defineScoutInput } from "@scouterna/ui-webc/dist/components/scout-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type ScoutBottomBarEvents = NonNullable<unknown>;

export const ScoutBottomBar: StencilReactComponent<ScoutBottomBarElement, ScoutBottomBarEvents> = /*@__PURE__*/ createComponent<ScoutBottomBarElement, ScoutBottomBarEvents>({
    tagName: 'scout-bottom-bar',
    elementClass: ScoutBottomBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutBottomBarEvents,
    defineCustomElement: defineScoutBottomBar
});

export type ScoutBottomBarItemEvents = { onScoutClick: EventName<CustomEvent<void>> };

export const ScoutBottomBarItem: StencilReactComponent<ScoutBottomBarItemElement, ScoutBottomBarItemEvents> = /*@__PURE__*/ createComponent<ScoutBottomBarItemElement, ScoutBottomBarItemEvents>({
    tagName: 'scout-bottom-bar-item',
    elementClass: ScoutBottomBarItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onScoutClick: 'scoutClick' } as ScoutBottomBarItemEvents,
    defineCustomElement: defineScoutBottomBarItem
});

export type ScoutButtonEvents = { onScoutClick: EventName<CustomEvent<void>> };

export const ScoutButton: StencilReactComponent<ScoutButtonElement, ScoutButtonEvents> = /*@__PURE__*/ createComponent<ScoutButtonElement, ScoutButtonEvents>({
    tagName: 'scout-button',
    elementClass: ScoutButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onScoutClick: 'scoutClick' } as ScoutButtonEvents,
    defineCustomElement: defineScoutButton
});

export type ScoutCardEvents = NonNullable<unknown>;

export const ScoutCard: StencilReactComponent<ScoutCardElement, ScoutCardEvents> = /*@__PURE__*/ createComponent<ScoutCardElement, ScoutCardEvents>({
    tagName: 'scout-card',
    elementClass: ScoutCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutCardEvents,
    defineCustomElement: defineScoutCard
});

export type ScoutCheckboxEvents = {
    onScoutCheckboxChecked: EventName<ScoutCheckboxCustomEvent<{
        checked: boolean;
        element: HTMLInputElement;
    }>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutCheckbox: StencilReactComponent<ScoutCheckboxElement, ScoutCheckboxEvents> = /*@__PURE__*/ createComponent<ScoutCheckboxElement, ScoutCheckboxEvents>({
    tagName: 'scout-checkbox',
    elementClass: ScoutCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutCheckboxChecked: 'scoutCheckboxChecked',
        on_fieldId: '_fieldId'
    } as ScoutCheckboxEvents,
    defineCustomElement: defineScoutCheckbox
});

export type ScoutFieldEvents = NonNullable<unknown>;

export const ScoutField: StencilReactComponent<ScoutFieldElement, ScoutFieldEvents> = /*@__PURE__*/ createComponent<ScoutFieldElement, ScoutFieldEvents>({
    tagName: 'scout-field',
    elementClass: ScoutFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutFieldEvents,
    defineCustomElement: defineScoutField
});

export type ScoutInputEvents = {
    onScoutInputChange: EventName<ScoutInputCustomEvent<{
        value: string;
        element: HTMLInputElement;
    }>>,
    onScoutBlur: EventName<CustomEvent<void>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutInput: StencilReactComponent<ScoutInputElement, ScoutInputEvents> = /*@__PURE__*/ createComponent<ScoutInputElement, ScoutInputEvents>({
    tagName: 'scout-input',
    elementClass: ScoutInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutInputChange: 'scoutInputChange',
        onScoutBlur: 'scoutBlur',
        on_fieldId: '_fieldId'
    } as ScoutInputEvents,
    defineCustomElement: defineScoutInput
});
