'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ScoutCheckboxCustomEvent, type ScoutInputCustomEvent, type ScoutSelectCustomEvent, type ScoutSwitchCustomEvent } from "@scouterna/ui-webc";
import { ScoutBottomBarItem as ScoutBottomBarItemElement, defineCustomElement as defineScoutBottomBarItem } from "@scouterna/ui-webc/dist/components/scout-bottom-bar-item.js";
import { ScoutBottomBar as ScoutBottomBarElement, defineCustomElement as defineScoutBottomBar } from "@scouterna/ui-webc/dist/components/scout-bottom-bar.js";
import { ScoutButton as ScoutButtonElement, defineCustomElement as defineScoutButton } from "@scouterna/ui-webc/dist/components/scout-button.js";
import { ScoutCard as ScoutCardElement, defineCustomElement as defineScoutCard } from "@scouterna/ui-webc/dist/components/scout-card.js";
import { ScoutCheckbox as ScoutCheckboxElement, defineCustomElement as defineScoutCheckbox } from "@scouterna/ui-webc/dist/components/scout-checkbox.js";
import { ScoutDivider as ScoutDividerElement, defineCustomElement as defineScoutDivider } from "@scouterna/ui-webc/dist/components/scout-divider.js";
import { ScoutField as ScoutFieldElement, defineCustomElement as defineScoutField } from "@scouterna/ui-webc/dist/components/scout-field.js";
import { ScoutInput as ScoutInputElement, defineCustomElement as defineScoutInput } from "@scouterna/ui-webc/dist/components/scout-input.js";
import { ScoutListViewItem as ScoutListViewItemElement, defineCustomElement as defineScoutListViewItem } from "@scouterna/ui-webc/dist/components/scout-list-view-item.js";
import { ScoutListView as ScoutListViewElement, defineCustomElement as defineScoutListView } from "@scouterna/ui-webc/dist/components/scout-list-view.js";
import { ScoutLoader as ScoutLoaderElement, defineCustomElement as defineScoutLoader } from "@scouterna/ui-webc/dist/components/scout-loader.js";
import { ScoutSelect as ScoutSelectElement, defineCustomElement as defineScoutSelect } from "@scouterna/ui-webc/dist/components/scout-select.js";
import { ScoutSwitch as ScoutSwitchElement, defineCustomElement as defineScoutSwitch } from "@scouterna/ui-webc/dist/components/scout-switch.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type ScoutBottomBarEvents = NonNullable<unknown>;

export const ScoutBottomBar: StencilReactComponent<ScoutBottomBarElement, ScoutBottomBarEvents> = /*@__PURE__*/ createComponent<ScoutBottomBarElement, ScoutBottomBarEvents>({
    tagName: 'scout-bottom-bar',
    elementClass: ScoutBottomBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutBottomBarEvents,
    defineCustomElement: defineScoutBottomBar
});

export type ScoutBottomBarItemEvents = { onScoutClick: EventName<CustomEvent<void>> };

export const ScoutBottomBarItem: StencilReactComponent<ScoutBottomBarItemElement, ScoutBottomBarItemEvents> = /*@__PURE__*/ createComponent<ScoutBottomBarItemElement, ScoutBottomBarItemEvents>({
    tagName: 'scout-bottom-bar-item',
    elementClass: ScoutBottomBarItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onScoutClick: 'scoutClick' } as ScoutBottomBarItemEvents,
    defineCustomElement: defineScoutBottomBarItem
});

export type ScoutButtonEvents = { onScoutClick: EventName<CustomEvent<void>> };

export const ScoutButton: StencilReactComponent<ScoutButtonElement, ScoutButtonEvents> = /*@__PURE__*/ createComponent<ScoutButtonElement, ScoutButtonEvents>({
    tagName: 'scout-button',
    elementClass: ScoutButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onScoutClick: 'scoutClick' } as ScoutButtonEvents,
    defineCustomElement: defineScoutButton
});

export type ScoutCardEvents = NonNullable<unknown>;

export const ScoutCard: StencilReactComponent<ScoutCardElement, ScoutCardEvents> = /*@__PURE__*/ createComponent<ScoutCardElement, ScoutCardEvents>({
    tagName: 'scout-card',
    elementClass: ScoutCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutCardEvents,
    defineCustomElement: defineScoutCard
});

export type ScoutCheckboxEvents = {
    onScoutCheckboxChecked: EventName<ScoutCheckboxCustomEvent<{
        checked: boolean;
        element: HTMLInputElement;
    }>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutCheckbox: StencilReactComponent<ScoutCheckboxElement, ScoutCheckboxEvents> = /*@__PURE__*/ createComponent<ScoutCheckboxElement, ScoutCheckboxEvents>({
    tagName: 'scout-checkbox',
    elementClass: ScoutCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutCheckboxChecked: 'scoutCheckboxChecked',
        on_fieldId: '_fieldId'
    } as ScoutCheckboxEvents,
    defineCustomElement: defineScoutCheckbox
});

export type ScoutDividerEvents = NonNullable<unknown>;

export const ScoutDivider: StencilReactComponent<ScoutDividerElement, ScoutDividerEvents> = /*@__PURE__*/ createComponent<ScoutDividerElement, ScoutDividerEvents>({
    tagName: 'scout-divider',
    elementClass: ScoutDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutDividerEvents,
    defineCustomElement: defineScoutDivider
});

export type ScoutFieldEvents = NonNullable<unknown>;

export const ScoutField: StencilReactComponent<ScoutFieldElement, ScoutFieldEvents> = /*@__PURE__*/ createComponent<ScoutFieldElement, ScoutFieldEvents>({
    tagName: 'scout-field',
    elementClass: ScoutFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutFieldEvents,
    defineCustomElement: defineScoutField
});

export type ScoutInputEvents = {
    onScoutInputChange: EventName<ScoutInputCustomEvent<{
        value: string;
        element: HTMLInputElement;
    }>>,
    onScoutBlur: EventName<CustomEvent<void>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutInput: StencilReactComponent<ScoutInputElement, ScoutInputEvents> = /*@__PURE__*/ createComponent<ScoutInputElement, ScoutInputEvents>({
    tagName: 'scout-input',
    elementClass: ScoutInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutInputChange: 'scoutInputChange',
        onScoutBlur: 'scoutBlur',
        on_fieldId: '_fieldId'
    } as ScoutInputEvents,
    defineCustomElement: defineScoutInput
});

export type ScoutListViewEvents = NonNullable<unknown>;

export const ScoutListView: StencilReactComponent<ScoutListViewElement, ScoutListViewEvents> = /*@__PURE__*/ createComponent<ScoutListViewElement, ScoutListViewEvents>({
    tagName: 'scout-list-view',
    elementClass: ScoutListViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutListViewEvents,
    defineCustomElement: defineScoutListView
});

export type ScoutListViewItemEvents = { onScoutClick: EventName<CustomEvent<void>> };

export const ScoutListViewItem: StencilReactComponent<ScoutListViewItemElement, ScoutListViewItemEvents> = /*@__PURE__*/ createComponent<ScoutListViewItemElement, ScoutListViewItemEvents>({
    tagName: 'scout-list-view-item',
    elementClass: ScoutListViewItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onScoutClick: 'scoutClick' } as ScoutListViewItemEvents,
    defineCustomElement: defineScoutListViewItem
});

export type ScoutLoaderEvents = NonNullable<unknown>;

export const ScoutLoader: StencilReactComponent<ScoutLoaderElement, ScoutLoaderEvents> = /*@__PURE__*/ createComponent<ScoutLoaderElement, ScoutLoaderEvents>({
    tagName: 'scout-loader',
    elementClass: ScoutLoaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ScoutLoaderEvents,
    defineCustomElement: defineScoutLoader
});

export type ScoutSelectEvents = {
    onScoutSelectChange: EventName<ScoutSelectCustomEvent<{
        value: string;
        element: HTMLSelectElement;
    }>>,
    onScoutBlur: EventName<CustomEvent<void>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutSelect: StencilReactComponent<ScoutSelectElement, ScoutSelectEvents> = /*@__PURE__*/ createComponent<ScoutSelectElement, ScoutSelectEvents>({
    tagName: 'scout-select',
    elementClass: ScoutSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutSelectChange: 'scoutSelectChange',
        onScoutBlur: 'scoutBlur',
        on_fieldId: '_fieldId'
    } as ScoutSelectEvents,
    defineCustomElement: defineScoutSelect
});

export type ScoutSwitchEvents = {
    onScoutSwitchToggled: EventName<ScoutSwitchCustomEvent<{
        toggled: boolean;
        element: HTMLInputElement;
    }>>,
    on_fieldId: EventName<CustomEvent<string>>
};

export const ScoutSwitch: StencilReactComponent<ScoutSwitchElement, ScoutSwitchEvents> = /*@__PURE__*/ createComponent<ScoutSwitchElement, ScoutSwitchEvents>({
    tagName: 'scout-switch',
    elementClass: ScoutSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onScoutSwitchToggled: 'scoutSwitchToggled',
        on_fieldId: '_fieldId'
    } as ScoutSwitchEvents,
    defineCustomElement: defineScoutSwitch
});
