/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ItemType } from "./components/bottom-bar-item/bottom-bar-item";
import { Variant } from "./components/button/button";
export { ItemType } from "./components/bottom-bar-item/bottom-bar-item";
export { Variant } from "./components/button/button";
export namespace Components {
    interface ScoutBottomBar {
    }
    interface ScoutBottomBarItem {
        "active"?: boolean;
        "href"?: string;
        "icon": string;
        "label": string;
        /**
          * @default "button"
         */
        "type": ItemType;
    }
    interface ScoutButton {
        "icon"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * @default "outlined"
         */
        "variant": Variant;
    }
}
export interface ScoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutButtonElement;
}
declare global {
    interface HTMLScoutBottomBarElement extends Components.ScoutBottomBar, HTMLStencilElement {
    }
    var HTMLScoutBottomBarElement: {
        prototype: HTMLScoutBottomBarElement;
        new (): HTMLScoutBottomBarElement;
    };
    interface HTMLScoutBottomBarItemElement extends Components.ScoutBottomBarItem, HTMLStencilElement {
    }
    var HTMLScoutBottomBarItemElement: {
        prototype: HTMLScoutBottomBarItemElement;
        new (): HTMLScoutBottomBarItemElement;
    };
    interface HTMLScoutButtonElementEventMap {
        "scoutClick": void;
    }
    interface HTMLScoutButtonElement extends Components.ScoutButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutButtonElementEventMap>(type: K, listener: (this: HTMLScoutButtonElement, ev: ScoutButtonCustomEvent<HTMLScoutButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutButtonElementEventMap>(type: K, listener: (this: HTMLScoutButtonElement, ev: ScoutButtonCustomEvent<HTMLScoutButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutButtonElement: {
        prototype: HTMLScoutButtonElement;
        new (): HTMLScoutButtonElement;
    };
    interface HTMLElementTagNameMap {
        "scout-bottom-bar": HTMLScoutBottomBarElement;
        "scout-bottom-bar-item": HTMLScoutBottomBarItemElement;
        "scout-button": HTMLScoutButtonElement;
    }
}
declare namespace LocalJSX {
    interface ScoutBottomBar {
    }
    interface ScoutBottomBarItem {
        "active"?: boolean;
        "href"?: string;
        "icon": string;
        "label": string;
        /**
          * @default "button"
         */
        "type"?: ItemType;
    }
    interface ScoutButton {
        "icon"?: string;
        "onScoutClick"?: (event: ScoutButtonCustomEvent<void>) => void;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * @default "outlined"
         */
        "variant"?: Variant;
    }
    interface IntrinsicElements {
        "scout-bottom-bar": ScoutBottomBar;
        "scout-bottom-bar-item": ScoutBottomBarItem;
        "scout-button": ScoutButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scout-bottom-bar": LocalJSX.ScoutBottomBar & JSXBase.HTMLAttributes<HTMLScoutBottomBarElement>;
            "scout-bottom-bar-item": LocalJSX.ScoutBottomBarItem & JSXBase.HTMLAttributes<HTMLScoutBottomBarItemElement>;
            "scout-button": LocalJSX.ScoutButton & JSXBase.HTMLAttributes<HTMLScoutButtonElement>;
        }
    }
}
