/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Page } from "./components/lab-sidebar/types";
export { Page } from "./components/lab-sidebar/types";
export namespace Components {
    interface LabLayout {
    }
    interface LabSidebar {
        /**
          * @default ""
         */
        "currentPage": string;
        /**
          * @default {}
         */
        "pages": Record<string, Page>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "test": { name: string };
    }
}
declare global {
    interface HTMLLabLayoutElement extends Components.LabLayout, HTMLStencilElement {
    }
    var HTMLLabLayoutElement: {
        prototype: HTMLLabLayoutElement;
        new (): HTMLLabLayoutElement;
    };
    interface HTMLLabSidebarElement extends Components.LabSidebar, HTMLStencilElement {
    }
    var HTMLLabSidebarElement: {
        prototype: HTMLLabSidebarElement;
        new (): HTMLLabSidebarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lab-layout": HTMLLabLayoutElement;
        "lab-sidebar": HTMLLabSidebarElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface LabLayout {
    }
    interface LabSidebar {
        /**
          * @default ""
         */
        "currentPage"?: string;
        /**
          * @default {}
         */
        "pages"?: Record<string, Page>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "test"?: { name: string };
    }
    interface IntrinsicElements {
        "lab-layout": LabLayout;
        "lab-sidebar": LabSidebar;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lab-layout": LocalJSX.LabLayout & JSXBase.HTMLAttributes<HTMLLabLayoutElement>;
            "lab-sidebar": LocalJSX.LabSidebar & JSXBase.HTMLAttributes<HTMLLabSidebarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
