/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ItemType } from "./components/bottom-bar-item/bottom-bar-item";
import { Variant } from "./components/button/button";
import { InputMode, InputType } from "./components/input/input";
import { ItemType as ItemType1 } from "./components/list-view-item/list-view-item";
export { ItemType } from "./components/bottom-bar-item/bottom-bar-item";
export { Variant } from "./components/button/button";
export { InputMode, InputType } from "./components/input/input";
export { ItemType as ItemType1 } from "./components/list-view-item/list-view-item";
export namespace Components {
    /**
     * The bottom bar component is used in the Jamboree26 app to provide
     * navigation at the bottom of the screen.
     */
    interface ScoutBottomBar {
    }
    /**
     * A bottom bar item used within the bottom bar for navigation. Should not be
     * used outside of a bottom bar.
     */
    interface ScoutBottomBarItem {
        /**
          * Whether the item is currently active. Should be set to true when the item represents the current page.
         */
        "active"?: boolean;
        /**
          * An optional link to navigate to when the item is clicked. Only used when `type` is set to "link".
         */
        "href"?: string;
        /**
          * An icon to display above the label. Must be an SVG string.
         */
        "icon": string;
        /**
          * The label to display below the icon.
         */
        "label": string;
        "rel"?: string;
        "target"?: string;
        /**
          * The type of the bottom bar item, either a button or a link.
          * @default "button"
         */
        "type": ItemType;
    }
    /**
     * A simple button component.
     */
    interface ScoutButton {
        "href"?: string;
        /**
          * An optional icon to display alongside the button text. Must be an SVG string.
         */
        "icon"?: string;
        "rel"?: string;
        "target"?: string;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset" | "link";
        /**
          * The variant primarily affects the color of the button.
          * @default "outlined"
         */
        "variant": Variant;
    }
    /**
     * A general surface to hold various types of content.
     */
    interface ScoutCard {
    }
    interface ScoutCheckbox {
        /**
          * Use this prop if you need to connect your checkbox with another element describing its use, other than the property label.
         */
        "ariaLabelledby": string;
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
    }
    interface ScoutDivider {
    }
    interface ScoutField {
        /**
          * Help text shown below the field.
         */
        "helpText"?: string;
        /**
          * Label shown above the field.
         */
        "label": string;
    }
    interface ScoutInput {
        /**
          * Whether the input is disabled. Disabled inputs are not editable, excluded from tab order and are not validated.
          * @default false
         */
        "disabled": boolean;
        /**
          * Input mode hints for devices with dynamic keyboards.
         */
        "inputmode"?: InputMode;
        /**
          * Regex pattern for input validation.
         */
        "pattern"?: string;
        /**
          * Type of input element. If you need a number input, read the accessibility section of this MDN article first: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/number#accessibility
          * @default "text"
         */
        "type": InputType;
        /**
          * Custom validation function run on top of the implicit validation performed by the browser. Return a string with the validation message to mark the input as invalid, or null to mark it as valid.
         */
        "validate"?: (value: string) => string | null;
        /**
          * Value of the input element, in case you want to control it yourself.
          * @default ""
         */
        "value": string;
    }
    interface ScoutListView {
    }
    interface ScoutListViewItem {
        "href"?: string;
        "icon"?: string;
        "primary"?: string;
        "rel"?: string;
        "secondary"?: string;
        "target"?: string;
        /**
          * @default "button"
         */
        "type": ItemType1;
    }
    interface ScoutSwitch {
        /**
          * Use this prop if you need to connect your switch with another element describing its use, other than the property label.
         */
        "ariaLabelledby": string;
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
        /**
          * Indicates whether the switch is toggled on or off.
          * @default false
         */
        "toggled": boolean;
    }
    interface ScoutTextArea {
        /**
          * @default false
         */
        "autofocus": boolean;
        "disabled"?: boolean;
        "form": string;
        "label"?: string;
        "maxLength"?: number;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "required"?: boolean;
        "value"?: string;
    }
}
export interface ScoutBottomBarItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutBottomBarItemElement;
}
export interface ScoutButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutButtonElement;
}
export interface ScoutCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutCheckboxElement;
}
export interface ScoutInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutInputElement;
}
export interface ScoutListViewItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutListViewItemElement;
}
export interface ScoutSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoutSwitchElement;
}
declare global {
    /**
     * The bottom bar component is used in the Jamboree26 app to provide
     * navigation at the bottom of the screen.
     */
    interface HTMLScoutBottomBarElement extends Components.ScoutBottomBar, HTMLStencilElement {
    }
    var HTMLScoutBottomBarElement: {
        prototype: HTMLScoutBottomBarElement;
        new (): HTMLScoutBottomBarElement;
    };
    interface HTMLScoutBottomBarItemElementEventMap {
        "scoutClick": void;
    }
    /**
     * A bottom bar item used within the bottom bar for navigation. Should not be
     * used outside of a bottom bar.
     */
    interface HTMLScoutBottomBarItemElement extends Components.ScoutBottomBarItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutBottomBarItemElementEventMap>(type: K, listener: (this: HTMLScoutBottomBarItemElement, ev: ScoutBottomBarItemCustomEvent<HTMLScoutBottomBarItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutBottomBarItemElementEventMap>(type: K, listener: (this: HTMLScoutBottomBarItemElement, ev: ScoutBottomBarItemCustomEvent<HTMLScoutBottomBarItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutBottomBarItemElement: {
        prototype: HTMLScoutBottomBarItemElement;
        new (): HTMLScoutBottomBarItemElement;
    };
    interface HTMLScoutButtonElementEventMap {
        "scoutClick": void;
    }
    /**
     * A simple button component.
     */
    interface HTMLScoutButtonElement extends Components.ScoutButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutButtonElementEventMap>(type: K, listener: (this: HTMLScoutButtonElement, ev: ScoutButtonCustomEvent<HTMLScoutButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutButtonElementEventMap>(type: K, listener: (this: HTMLScoutButtonElement, ev: ScoutButtonCustomEvent<HTMLScoutButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutButtonElement: {
        prototype: HTMLScoutButtonElement;
        new (): HTMLScoutButtonElement;
    };
    /**
     * A general surface to hold various types of content.
     */
    interface HTMLScoutCardElement extends Components.ScoutCard, HTMLStencilElement {
    }
    var HTMLScoutCardElement: {
        prototype: HTMLScoutCardElement;
        new (): HTMLScoutCardElement;
    };
    interface HTMLScoutCheckboxElementEventMap {
        "scoutCheckboxChecked": {
    checked: boolean;
    element: HTMLInputElement;
  };
        "_fieldId": string;
    }
    interface HTMLScoutCheckboxElement extends Components.ScoutCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutCheckboxElementEventMap>(type: K, listener: (this: HTMLScoutCheckboxElement, ev: ScoutCheckboxCustomEvent<HTMLScoutCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutCheckboxElementEventMap>(type: K, listener: (this: HTMLScoutCheckboxElement, ev: ScoutCheckboxCustomEvent<HTMLScoutCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutCheckboxElement: {
        prototype: HTMLScoutCheckboxElement;
        new (): HTMLScoutCheckboxElement;
    };
    interface HTMLScoutDividerElement extends Components.ScoutDivider, HTMLStencilElement {
    }
    var HTMLScoutDividerElement: {
        prototype: HTMLScoutDividerElement;
        new (): HTMLScoutDividerElement;
    };
    interface HTMLScoutFieldElement extends Components.ScoutField, HTMLStencilElement {
    }
    var HTMLScoutFieldElement: {
        prototype: HTMLScoutFieldElement;
        new (): HTMLScoutFieldElement;
    };
    interface HTMLScoutInputElementEventMap {
        "scoutInputChange": {
    value: string;
    element: HTMLInputElement;
  };
        "scoutBlur": void;
        "_fieldId": string;
    }
    interface HTMLScoutInputElement extends Components.ScoutInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutInputElementEventMap>(type: K, listener: (this: HTMLScoutInputElement, ev: ScoutInputCustomEvent<HTMLScoutInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutInputElementEventMap>(type: K, listener: (this: HTMLScoutInputElement, ev: ScoutInputCustomEvent<HTMLScoutInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutInputElement: {
        prototype: HTMLScoutInputElement;
        new (): HTMLScoutInputElement;
    };
    interface HTMLScoutListViewElement extends Components.ScoutListView, HTMLStencilElement {
    }
    var HTMLScoutListViewElement: {
        prototype: HTMLScoutListViewElement;
        new (): HTMLScoutListViewElement;
    };
    interface HTMLScoutListViewItemElementEventMap {
        "scoutClick": void;
    }
    interface HTMLScoutListViewItemElement extends Components.ScoutListViewItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutListViewItemElementEventMap>(type: K, listener: (this: HTMLScoutListViewItemElement, ev: ScoutListViewItemCustomEvent<HTMLScoutListViewItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutListViewItemElementEventMap>(type: K, listener: (this: HTMLScoutListViewItemElement, ev: ScoutListViewItemCustomEvent<HTMLScoutListViewItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutListViewItemElement: {
        prototype: HTMLScoutListViewItemElement;
        new (): HTMLScoutListViewItemElement;
    };
    interface HTMLScoutSwitchElementEventMap {
        "scoutSwitchToggled": {
    toggled: boolean;
    element: HTMLInputElement;
  };
        "_fieldId": string;
    }
    interface HTMLScoutSwitchElement extends Components.ScoutSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoutSwitchElementEventMap>(type: K, listener: (this: HTMLScoutSwitchElement, ev: ScoutSwitchCustomEvent<HTMLScoutSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoutSwitchElementEventMap>(type: K, listener: (this: HTMLScoutSwitchElement, ev: ScoutSwitchCustomEvent<HTMLScoutSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoutSwitchElement: {
        prototype: HTMLScoutSwitchElement;
        new (): HTMLScoutSwitchElement;
    };
    interface HTMLScoutTextAreaElement extends Components.ScoutTextArea, HTMLStencilElement {
    }
    var HTMLScoutTextAreaElement: {
        prototype: HTMLScoutTextAreaElement;
        new (): HTMLScoutTextAreaElement;
    };
    interface HTMLElementTagNameMap {
        "scout-bottom-bar": HTMLScoutBottomBarElement;
        "scout-bottom-bar-item": HTMLScoutBottomBarItemElement;
        "scout-button": HTMLScoutButtonElement;
        "scout-card": HTMLScoutCardElement;
        "scout-checkbox": HTMLScoutCheckboxElement;
        "scout-divider": HTMLScoutDividerElement;
        "scout-field": HTMLScoutFieldElement;
        "scout-input": HTMLScoutInputElement;
        "scout-list-view": HTMLScoutListViewElement;
        "scout-list-view-item": HTMLScoutListViewItemElement;
        "scout-switch": HTMLScoutSwitchElement;
        "scout-text-area": HTMLScoutTextAreaElement;
    }
}
declare namespace LocalJSX {
    /**
     * The bottom bar component is used in the Jamboree26 app to provide
     * navigation at the bottom of the screen.
     */
    interface ScoutBottomBar {
    }
    /**
     * A bottom bar item used within the bottom bar for navigation. Should not be
     * used outside of a bottom bar.
     */
    interface ScoutBottomBarItem {
        /**
          * Whether the item is currently active. Should be set to true when the item represents the current page.
         */
        "active"?: boolean;
        /**
          * An optional link to navigate to when the item is clicked. Only used when `type` is set to "link".
         */
        "href"?: string;
        /**
          * An icon to display above the label. Must be an SVG string.
         */
        "icon": string;
        /**
          * The label to display below the icon.
         */
        "label": string;
        "onScoutClick"?: (event: ScoutBottomBarItemCustomEvent<void>) => void;
        "rel"?: string;
        "target"?: string;
        /**
          * The type of the bottom bar item, either a button or a link.
          * @default "button"
         */
        "type"?: ItemType;
    }
    /**
     * A simple button component.
     */
    interface ScoutButton {
        "href"?: string;
        /**
          * An optional icon to display alongside the button text. Must be an SVG string.
         */
        "icon"?: string;
        "onScoutClick"?: (event: ScoutButtonCustomEvent<void>) => void;
        "rel"?: string;
        "target"?: string;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset" | "link";
        /**
          * The variant primarily affects the color of the button.
          * @default "outlined"
         */
        "variant"?: Variant;
    }
    /**
     * A general surface to hold various types of content.
     */
    interface ScoutCard {
    }
    interface ScoutCheckbox {
        /**
          * Use this prop if you need to connect your checkbox with another element describing its use, other than the property label.
         */
        "ariaLabelledby"?: string;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        "onScoutCheckboxChecked"?: (event: ScoutCheckboxCustomEvent<{
    checked: boolean;
    element: HTMLInputElement;
  }>) => void;
        /**
          * Internal event used for form field association.
         */
        "on_fieldId"?: (event: ScoutCheckboxCustomEvent<string>) => void;
    }
    interface ScoutDivider {
    }
    interface ScoutField {
        /**
          * Help text shown below the field.
         */
        "helpText"?: string;
        /**
          * Label shown above the field.
         */
        "label": string;
    }
    interface ScoutInput {
        /**
          * Whether the input is disabled. Disabled inputs are not editable, excluded from tab order and are not validated.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Input mode hints for devices with dynamic keyboards.
         */
        "inputmode"?: InputMode;
        "onScoutBlur"?: (event: ScoutInputCustomEvent<void>) => void;
        "onScoutInputChange"?: (event: ScoutInputCustomEvent<{
    value: string;
    element: HTMLInputElement;
  }>) => void;
        /**
          * Internal event used for form field association.
         */
        "on_fieldId"?: (event: ScoutInputCustomEvent<string>) => void;
        /**
          * Regex pattern for input validation.
         */
        "pattern"?: string;
        /**
          * Type of input element. If you need a number input, read the accessibility section of this MDN article first: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/number#accessibility
          * @default "text"
         */
        "type"?: InputType;
        /**
          * Custom validation function run on top of the implicit validation performed by the browser. Return a string with the validation message to mark the input as invalid, or null to mark it as valid.
         */
        "validate"?: (value: string) => string | null;
        /**
          * Value of the input element, in case you want to control it yourself.
          * @default ""
         */
        "value"?: string;
    }
    interface ScoutListView {
    }
    interface ScoutListViewItem {
        "href"?: string;
        "icon"?: string;
        "onScoutClick"?: (event: ScoutListViewItemCustomEvent<void>) => void;
        "primary"?: string;
        "rel"?: string;
        "secondary"?: string;
        "target"?: string;
        /**
          * @default "button"
         */
        "type"?: ItemType1;
    }
    interface ScoutSwitch {
        /**
          * Use this prop if you need to connect your switch with another element describing its use, other than the property label.
         */
        "ariaLabelledby"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        "onScoutSwitchToggled"?: (event: ScoutSwitchCustomEvent<{
    toggled: boolean;
    element: HTMLInputElement;
  }>) => void;
        /**
          * Internal event used for form field association.
         */
        "on_fieldId"?: (event: ScoutSwitchCustomEvent<string>) => void;
        /**
          * Indicates whether the switch is toggled on or off.
          * @default false
         */
        "toggled"?: boolean;
    }
    interface ScoutTextArea {
        /**
          * @default false
         */
        "autofocus"?: boolean;
        "disabled"?: boolean;
        "form"?: string;
        "label"?: string;
        "maxLength"?: number;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "required"?: boolean;
        "value"?: string;
    }
    interface IntrinsicElements {
        "scout-bottom-bar": ScoutBottomBar;
        "scout-bottom-bar-item": ScoutBottomBarItem;
        "scout-button": ScoutButton;
        "scout-card": ScoutCard;
        "scout-checkbox": ScoutCheckbox;
        "scout-divider": ScoutDivider;
        "scout-field": ScoutField;
        "scout-input": ScoutInput;
        "scout-list-view": ScoutListView;
        "scout-list-view-item": ScoutListViewItem;
        "scout-switch": ScoutSwitch;
        "scout-text-area": ScoutTextArea;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The bottom bar component is used in the Jamboree26 app to provide
             * navigation at the bottom of the screen.
             */
            "scout-bottom-bar": LocalJSX.ScoutBottomBar & JSXBase.HTMLAttributes<HTMLScoutBottomBarElement>;
            /**
             * A bottom bar item used within the bottom bar for navigation. Should not be
             * used outside of a bottom bar.
             */
            "scout-bottom-bar-item": LocalJSX.ScoutBottomBarItem & JSXBase.HTMLAttributes<HTMLScoutBottomBarItemElement>;
            /**
             * A simple button component.
             */
            "scout-button": LocalJSX.ScoutButton & JSXBase.HTMLAttributes<HTMLScoutButtonElement>;
            /**
             * A general surface to hold various types of content.
             */
            "scout-card": LocalJSX.ScoutCard & JSXBase.HTMLAttributes<HTMLScoutCardElement>;
            "scout-checkbox": LocalJSX.ScoutCheckbox & JSXBase.HTMLAttributes<HTMLScoutCheckboxElement>;
            "scout-divider": LocalJSX.ScoutDivider & JSXBase.HTMLAttributes<HTMLScoutDividerElement>;
            "scout-field": LocalJSX.ScoutField & JSXBase.HTMLAttributes<HTMLScoutFieldElement>;
            "scout-input": LocalJSX.ScoutInput & JSXBase.HTMLAttributes<HTMLScoutInputElement>;
            "scout-list-view": LocalJSX.ScoutListView & JSXBase.HTMLAttributes<HTMLScoutListViewElement>;
            "scout-list-view-item": LocalJSX.ScoutListViewItem & JSXBase.HTMLAttributes<HTMLScoutListViewItemElement>;
            "scout-switch": LocalJSX.ScoutSwitch & JSXBase.HTMLAttributes<HTMLScoutSwitchElement>;
            "scout-text-area": LocalJSX.ScoutTextArea & JSXBase.HTMLAttributes<HTMLScoutTextAreaElement>;
        }
    }
}
